In [3]:
! pip install tabula
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import warnings
warnings.filterwarnings('ignore')
import os
import glob
#!pip install --upgrade uncertainties
from uncertainties import ufloat
from uncertainties import unumpy
from uncertainties import umath
from uncertainties.umath import * # Imports sin()
import statistics as st
from scipy.optimize import curve_fit
import matplotlib as mpl
import tabula
from scipy.spatial.distance import cdist
from sklearn.preprocessing import StandardScaler
from scipy.spatial import distance
import statsmodels.api as sm
from scipy.stats import pearsonr
from scipy.stats import linregress
from scipy import stats


pallete = 'viridis'
from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
from matplotlib.ticker import FormatStrFormatter
font = {'color':  'black', 'weight': 'normal','size': 14}

Collecting tabula
  Downloading tabula-1.0.5.tar.gz (9.5 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: setuptools in c:\users\ruan\anaconda3\lib\site-packages (from tabula) (69.5.1)
Requirement already satisfied: numpy in c:\users\ruan\anaconda3\lib\site-packages (from tabula) (1.26.4)
Building wheels for collected packages: tabula
  Building wheel for tabula (setup.py): started
  Building wheel for tabula (setup.py): finished with status 'done'
  Created wheel for tabula: filename=tabula-1.0.5-py3-none-any.whl size=10602 sha256=3ddad4c2c8961c89c427c31abcafe74538293f0a89de4255b35aeac4749fdf7d
  Stored in directory: c:\users\ruan\appdata\local\pip\cache\wheels\02\36\f9\1af7331f3459ce65735775e24bfe68e3ea9cac5e5b23b0b42c
Successfully built tabula
Installing collected packages: tabula
Successfully installed tabula-1.0.5

# Donada

In [4]:
donada = pd.read_fwf('Donada.dat',)
donada.loc[donada.shape[0]]=donada.columns
colunas = ['Cluster','RAdeg','DEdeg','GLON','GLAT','r50',\
           'plx','e_plx','logAgeNN','AVNN','DistPc',\
           'X','Y','Z','Rgc','nbMSmemb','BP-RP0min',\
          'BP-RP0max','MSwidth','MassMin','MassMax','MassMean',\
          'fbqlim0.6', 'E_fbqlim0.6', 'e_fbqlim0.6',\
          'DG','E_DG', 'e_DG', 'sS','E_sS','e_sS', 'sB','E_sB',\
          'e_sB','fbtotqlim0.6','E_fbtotqlim0.6','e_fbtotqlim0.6']
donada.columns=colunas
donada.index=donada['Cluster']
donada.drop(columns='Cluster', inplace=True)
donada['fbtotqlim0.6'] = donada['fbtotqlim0.6'].astype(float)
donada.sort_index(inplace=True)
donada.head()

FileNotFoundError: [Errno 2] No such file or directory: 'Donada.dat'

In [4]:
Jedvahj = pd.read_csv('Jedvahj.txt',sep=',', index_col=None)
Jedvahj['Name'] = Jedvahj.index
Jedvahj.replace(to_replace=' ', value='_', regex=True, inplace= True)
Jedvahj.index=Jedvahj['Name']
Jedvahj.head()

,Name,log(age),DM,Metallicity,E(B-V),Core Radius,N _relax,Total Members,fb,${ \mathcal S }{ \mathcal I }$,Unnamed: 10
Name,,,,,,,,,,,
IC_4651,IC_4651,9.77,0.10,0.12,2.5,0.66,8.89,960,0.16,0.3_+or-_0.1,NaN
IC_4756,IC_4756,8.40,0.00,0.20,6.0,0.83,7.48,543,0.31,-0.24_+or-_0.08,\t
NGC_0188,NGC_0188,11.30,0.11,0.08,2.1,1.12,10.29,1181,0.25,\t0.11_+or-_0.08\t,NaN
NGC_0752,NGC_0752,8.26,0.12,0.05,6.2,0.81,11.23,433,0.19,\t-0.05_+or-_0.16\t,NaN
NGC_1039,NGC_1039,8.53,0.10,0.08,5.6,0.83,1.04,764,0.17,\t0.24_+or-_0.13\t,NaN

In [5]:
Niu = lista_tabelas = tabula.read_pdf('Binary Fraction Estimation of Main-sequence Stars in 12 Open Clusters.pdf', pages="all")
Niu = Niu[4]
Niu.dropna(inplace=True)
Niu[['Cluster','fbin']] = Niu[['Cluster','fbin']].astype('string')
Niu.replace(to_replace=' ', value='_', regex=True, inplace= True)
Niu.replace(to_replace='±[0-9]', value='', regex=True, inplace= True)
Niu['fbin'] = Niu['fbin'].astype(float)
Niu.index=Niu['Cluster']

Error importing jpype dependencies. Fallback to subprocess.
No module named 'jpype'

In [5]:
lista_tabelas = tabula.read_pdf('On the Determination of Stellar Mass and Binary Fraction of Open Clusters within 500 pc from the.pdf', pages="all")

AttributeError: module 'tabula' has no attribute 'read_pdf'

In [7]:
Jiang = lista_tabelas[-2]
Jiang.index=Jiang['Name ref']
Jiang.replace(to_replace=' ', value='_', regex=True, inplace= True)
Jiang.index=Jiang['Name ref']
Jiang.dropna(inplace=True)
Jiang

,Name,fb,Name ref,fb ref,Reference
Name ref,,,,,
ASCC_16,OCSN_127,0.17,ASCC_16,0.153±_0.033,Donada_et_al._(2023)
ASCC_19,OCSN_128,0.10,ASCC_19,0.088±_0.035,Donada_et_al._(2023)
ASCC_21,OCSN_129,0.15,ASCC_21,0.207±_0.116,Donada_et_al._(2023)
ASCC_41,OCSN_130,0.15,ASCC_41,0.143±_0.035,Donada_et_al._(2023)
ASCC_58,OCSN_131,0.15,ASCC_58,0.073±_0.020,Donada_et_al._(2023)
ASCC_124,OCSN_134,0.21,ASCC_124,0.197±_0.087,Donada_et_al._(2023)
ASCC_127,OCSN_135,0.16,ASCC_127,0.146±_0.038,Donada_et_al._(2023)
Alessi_3,OCSN_137,0.19,Alessi_3,0.209±_0.044,Donada_et_al._(2023)
Alessi_9,OCSN_139,0.26,Alessi_9,0.121±_0.033,Donada_et_al._(2023)
Alessi_24,OCSN_142,0.09,Alessi_24,0.068±_0.022,Donada_et_al._(2023)
BH_23,OCSN_146,0.17,BH_23,0.134±_0.044,Donada_et_al._(2023)
BH_164,OCSN_148,0.15,BH_164,0.106±_0.025,Donada_et_al._(2023)
Collinder_140,OCSN_191,0.12,Collinder_140,0.158±_0.042,Donada_et_al._(2023)
UBC_17b,OCSN_194,0.22,UBC_17b,0.218±_0.051,Donada_et_al._(2023)
Gulliver_9,OCSN_195,0.26,Gulliver_9,0.225±_0.043,Donada_et_al._(2023)
IC_4756,OCSN_207,0.33,IC_4756,0.31±_0.03,Jadhav_et_al._(2021)
UBC_7,OCSN_210,0.09,UBC_7,0.114±_0.043,Donada_et_al._(2023)
Mamajek_4,OCSN_217,0.16,Mamajek_4,0.125±_0.022,Donada_et_al._(2023)
Pleiades,OCSN_219,0.13,Pleiades,0.14±_0.02,Jadhav_et_al._(2021)
NGC_752,OCSN_221,0.25,NGC_752,0.19±_0.03,Jadhav_et_al._(2021)
NGC_1039,OCSN_222,0.14,NGC_1039,0.17±_0.02,Jadhav_et_al._(2021)
NGC_2281,OCSN_228,0.12,NGC_2281,0.101±_0.056,Donada_et_al._(2023)
NGC_2422,OCSN_229,0.11,NGC_2422,0.14±_0.02,Jadhav_et_al._(2021)
NGC_2451B,OCSN_231,0.14,NGC_2451B,0.099±_0.025,Donada_et_al._(2023)
NGC_2516,OCSN_232,0.16,NGC_2516,0.16±_0.01,Jadhav_et_al._(2021)
NGC_2547,OCSN_233,0.20,NGC_2547,0.22±_0.04,Jadhav_et_al._(2021)
NGC_3228,OCSN_235,0.17,NGC_3228,0.094±_0.045,Donada_et_al._(2023)
NGC_3532,OCSN_236,0.20,NGC_3532,0.13±_0.01,Jadhav_et_al._(2021)
NGC_6281,OCSN_238,0.23,NGC_6281,0.27±_0.02,Jadhav_et_al._(2021)
NGC_6405,OCSN_239,0.18,NGC_6405,0.17±_0.02,Jadhav_et_al._(2021)
NGC_7092,OCSN_243,0.21,NGC_7092,0.104±_0.025,Donada_et_al._(2023)
Platais_3,OCSN_250,0.15,Platais_3,0.086±_0.033,Donada_et_al._(2023)
RSG_5,OCSN_256,0.18,RSG_5,0.161±_0.033,Donada_et_al._(2023)
Ruprecht_147,OCSN_261,0.33,Ruprecht_147,0.177±_0.042,Donada_et_al._(2023)
Stephenson_1,OCSN_263,0.17,Stephenson_1,0.255±_0.060,Donada_et_al._(2023)
Stock_12,OCSN_267,0.17,Stock_12,0.141±_0.035,Donada_et_al._(2023)
Teutsch_35,OCSN_275,0.13,Teutsch_35,0.081±_0.024,Donada_et_al._(2023)
Trumpler_10,OCSN_276,0.15,Trumpler_10,0.12±_0.02,Jadhav_et_al._(2021)
UBC_1,OCSN_278,0.10,UBC_1,0.104±_0.032,Donada_et_al._(2023)
UBC_8,OCSN_279,0.20,UBC_8,0.245±_0.041,Donada_et_al._(2023)
UBC_17a,OCSN_283,0.14,UBC_17a,0.082±_0.025,Donada_et_al._(2023)
UBC_32,OCSN_288,0.23,UBC_32,0.186±_0.041,Donada_et_al._(2023)
UPK_535,OCSN_312,0.20,UPK_535,0.133±_0.039,Donada_et_al._(2023)
UPK_545,OCSN_314,0.15,UPK_545,0.085±_0.021,Donada_et_al._(2023)
UPK_612,OCSN_319,0.15,UPK_612,0.132±_0.049,Donada_et_al._(2023)

In [8]:
# Leitura dos dados
data = pd.read_csv('data.csv', index_col='Cluster')
data['q'] = data.comp_mass/data.mass
df = pd.read_csv('log-results-eDR3-MF_integrada.csv', index_col='Cluster')

In [9]:
def fb_donada(df):
    if isinstance(df, pd.Series):
        df = df.to_frame().T  # transforma em DataFrame de 1 linha
    sistemas_multiplos = len(df[df.q>0.6])
    sistemas_totais = len(df)+len(df[df.q<=0.6])
    return sistemas_multiplos/sistemas_totais

def fb_jedhav(df):
    if isinstance(df, pd.Series):
        df = df.to_frame().T  # transforma em DataFrame de 1 linha
    sistemas_multiplos = len(df[df.q>0.6])
    sistemas_totais = len(df)+len(df[df.q<=0.6])
    return sistemas_multiplos/sistemas_totais

def fb_jiang(df):
    if isinstance(df, pd.Series):
        df = df.to_frame().T  # transforma em DataFrame de 1 linha
    sistemas_multiplos = len(df[df.q>0.5])
    sistemas_totais = len(df)+len(df[df.q<=0.5])
    return sistemas_multiplos/sistemas_totais

In [156]:
columns = ['fb_donada', 'er_fb_donada','fb_donada_ref', 'er_fb_donada_ref',
'fb_jedhav', 'er_fb_jedhav','fb_jedhav_ref', 'er_fb_jedhav_ref',
'fb_jiang', 'er_fb_jiang','fb_jiang_ref', 'er_fb_jiang_ref',
'fb_niu', 'er_fb_niu','fb_niu_ref', 'er_fb_niu_ref',
'fb_mimo', 'er_fb_mimo','fb_mimo_ref', 'er_fb_mimo_ref',]
comparacao = pd.DataFrame(columns=columns, index=data.index.unique())


aux =

In [160]:
for cluster in df.index:
    au
    aux_donada = fb_donada()

for cluster in comparacao.index:
    if cluster in donada.index:
        
        comparacao.loc[cluster, 'fb_donada'] = fb_donada(data.loc[cluster])
        comparacao.loc[cluster, 'fb_donada_ref'] = donada.loc[cluster, 'fbtotqlim0.6']
        comparacao.loc[cluster, 'er_fb_donada_ref'] = float(donada.loc[cluster, 'e_fbtotqlim0.6'])
        comparacao.loc[cluster, 'er_fb_donada'] = comparacao.loc[cluster, 'fb_donada']*np.sqrt(1/len(data.loc[cluster])+1/len(data[data.q>0].loc[cluster]))
        
    if cluster in Jedvahj.index:
        comparacao.loc[cluster, 'fb_jedhav'] = fb_donada(data[data.mass<3.6].loc[cluster])
        comparacao.loc[cluster, 'fb_jedhav_ref'] = Jedvahj.loc[cluster, 'fb']
        comparacao.loc[cluster, 'er_fb_jedhav'] = comparacao.loc[cluster, 'fb_jedhav']*np.sqrt(1/len(data.loc[cluster])+1/len(data[data.q>0].loc[cluster]))

    if cluster in Niu.index:
        comparacao.loc[cluster, 'fb_niu'] = frac_bin(data.loc[cluster])
        comparacao.loc[cluster, 'fb_niu_ref'] = float(Niu.loc[cluster, 'fbin'])/100
        comparacao.loc[cluster, 'er_fb_niu'] = comparacao.loc[cluster, 'fb_niu']*np.sqrt(1/len(data.loc[cluster])+1/len(data[data.q>0].loc[cluster]))

    if cluster in Jiang.index:
        comparacao.loc[cluster, 'fb_jiang'] = fb_jiang(data.loc[cluster])
        comparacao.loc[cluster, 'fb_jiang_ref'] = float(Jiang.loc[cluster, 'fb'])
        comparacao.loc[cluster, 'er_fb_jiang'] = comparacao.loc[cluster, 'fb_jiang']*np.sqrt(1/len(data.loc[cluster])+1/len(data[data.q>0].loc[cluster]))

In [177]:
#MIMO
aglomerados = ['ASCC_21','Trumpler_3','Roslund_6','NGC_2287',\
              'NGC_2482',]
fb = [0.4,0.46,0.41,0.30,0.44]
e_fb = [0.03,0.05,0.03,0.03,0.06]

def fb_mimo(df):
    if isinstance(df, pd.Series):
        df = df.to_frame().T  # transforma em DataFrame de 1 linha
    sistemas_multiplos = len(df[df.q>0.2])
    sistemas_totais = len(df)+len(df[df.q<=0.2])
    return sistemas_multiplos/sistemas_totais

for i in range(0,len(aglomerados)):
    comparacao.loc[aglomerados[i], 'fb_mimo'] = fb_mimo(data.loc[aglomerados[i]])
    comparacao.loc[aglomerados[i], 'fb_mimo_ref'] = fb[i]
    comparacao.loc[aglomerados[i], 'er_fb_mimo_ref'] = e_fb[i]
    comparacao.loc[aglomerados[i], 'er_fb_mimo'] = comparacao.loc[aglomerados[i], 'fb_mimo']*np.sqrt(1/len(data.loc[aglomerados[i]])+1/len(data[data.q>0].loc[aglomerados[i]]))

In [178]:
def corrigir_erro(fb, e_fb):
    if fb + e_fb > 1:
        return fb -1
    else:
        return e_fb
col = ['fb_donada', 'fb_jedhav', 'fb_jiang', 'fb_niu', 'fb_mimo']
for i in range(0, len(col)):
    comparacao['er_'+col[i]+'_s'] = comparacao.apply(lambda row: corrigir_erro(row[col[i]], row['er_'+col[i]]), axis=1)

In [1]:
fig, axs = plt.subplots(2, 2, figsize=(10, 10), )

# Plot Donada
sns.scatterplot(
    data=comparacao, y='fb_donada', x='fb_donada_ref',
    color='b', marker='.', ax=axs[0, 0], label='Donada et al., 2023'
)

axs[0, 0].errorbar(comparacao['fb_donada_ref'], comparacao['fb_donada'],
    yerr=[comparacao['er_fb_donada'], comparacao['er_fb_donada_s']],
    fmt='none', ecolor='lightblue', elinewidth=.5, capsize=.5, alpha=0.5
)

# Plot Jadhav
sns.scatterplot(
    data=comparacao, y='fb_jedhav', x='fb_jedhav_ref',
    color='r', marker='v', ax=axs[0, 0], label='Jadhav et al., 2021'
)

axs[0, 0].errorbar(comparacao['fb_jedhav_ref'], comparacao['fb_jedhav'],
    yerr=[comparacao['er_fb_jedhav'],comparacao['er_fb_jedhav_s']],
    fmt='none', ecolor='red', elinewidth=.5, capsize=.5, alpha=0.5
)

#Plot Jiang

sns.scatterplot(data=comparacao, y='fb_jiang', x='fb_jiang_ref', c='r', ax=axs[0,1])
axs[0,1].legend(labels=['Jiang,2024'])

axs[0, 1].errorbar(comparacao['fb_jiang_ref'], comparacao['fb_jiang'],
    yerr=[comparacao['er_fb_jiang'],comparacao['er_fb_jiang_s']],
    fmt='none', ecolor='red', elinewidth=.5, capsize=.5, alpha=0.5
)

#Plot Niu Shao


sns.scatterplot(data=comparacao, y='fb_mimo', x='fb_mimo_ref', c='g', ax=axs[1,0])
axs[1,0].legend(labels=['Li; Shao, 2022'])

axs[1, 0].errorbar(comparacao['fb_mimo_ref'], comparacao['fb_mimo'],
    yerr=[comparacao['er_fb_mimo'],comparacao['er_fb_mimo_s']],
    fmt='none', ecolor='g', elinewidth=.5, capsize=.5, alpha=0.5
)
#Plot Niu

sns.scatterplot(data=comparacao, y='fb_niu', x='fb_niu_ref', c='orange', marker='o', ax = axs[1,1])
axs[1,1].legend(labels=['Niu; Wang; Fu, 2020' ])

axs[1, 1].errorbar(comparacao['fb_niu_ref'], comparacao['fb_niu'],
    yerr=[comparacao['er_fb_niu'], comparacao['er_fb_niu_s']], 
    fmt='none', ecolor='y', elinewidth=.5, capsize=.5, alpha=0.5
)



# Linha y = x
axs[0, 0].plot([0, 1], [0, 1], linestyle='dotted', color='k', alpha=0.3)
axs[0, 1].plot([0, 1], [0, 1], linestyle='dotted', color='k', alpha=0.3)
axs[1, 1].plot([0, 1], [0, 1], linestyle='dotted', color='k', alpha=0.3)
axs[1, 0].plot([0, 1], [0, 1], linestyle='dotted', color='k', alpha=0.3)


# Legenda e eixos
axs[0, 0].set_ylabel(r'$f_b$ (q > 0.6)', fontdict=font)
axs[0, 0].set_xlabel(r'$f_{b,\mathrm{Ref}}$ (q > 0.6)', fontdict=font)

axs[1, 0].set_ylabel(r'$f_b$ (q > 0.2)', fontdict=font)
axs[1, 0].set_xlabel(r'$f_{b,\mathrm{Ref}} (q > 0.2)$', fontdict=font)

axs[0, 1].set_ylabel(r'$f_b$ (q > 0.5)', fontdict=font)
axs[0, 1].set_xlabel(r'$f_{b,\mathrm{Ref}} (q > 0.5)$', fontdict=font)

axs[1, 1].set_ylabel(r'$f_b$', fontdict=font)
axs[1, 1].set_xlabel(r'$f_{b,\mathrm{Ref}}$', fontdict=font)


axs[0, 0].set_xlim(0, 1)
axs[0, 0].set_ylim(0, 1)

fig.subplots_adjust(wspace=0.3) 
fig.subplots_adjust(hspace=0.3) 

plt.savefig('clusters_properties.png',bbox_inches='tight', dpi=300)
plt.show()

NameError: name 'plt' is not defined