In [3]:
#! pip install tabula-py
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import sys
from pathlib import Path

sys.path.append(str(Path("../scripts").resolve()))
from functions import *

pallete = 'viridis'
font = {'color':  'black', 'weight': 'normal','size': 14}

patch = '/home/ruan/Mestrado/Referencias/'

data = pd.read_csv('../results/data.csv', index_col='Cluster')
df = pd.read_csv('../results/results.csv', index_col='Cluster')

In [4]:
Niu = pd.read_csv(patch + "Niu.txt", index_col='Cluster')
Niu = Niu[['fbin', 'fbin_err']]

donada = pd.read_fwf(patch + 'Donada.dat',)
donada.loc[donada.shape[0]]=donada.columns
colunas = ['Cluster','RAdeg','DEdeg','GLON','GLAT','r50',\
           'plx','e_plx','logAgeNN','AVNN','DistPc',\
           'X','Y','Z','Rgc','nbMSmemb','BP-RP0min',\
          'BP-RP0max','MSwidth','MassMin','MassMax','MassMean',\
          'fbqlim0.6', 'E_fbqlim0.6', 'e_fbqlim0.6',\
          'DG','E_DG', 'e_DG', 'sS','E_sS','e_sS', 'sB','E_sB',\
          'e_sB','fbtotqlim0.6','E_fbtotqlim0.6','e_fbtotqlim0.6']
donada.columns=colunas
donada.index=donada['Cluster']
donada.drop(columns='Cluster', inplace=True)
donada['fbtotqlim0.6'] = donada['fbtotqlim0.6'].astype(float)
donada['e_fbtotqlim0.6'] = donada['e_fbtotqlim0.6'].astype(float)
donada.sort_index(inplace=True)
donada = donada[['fbtotqlim0.6', 'e_fbtotqlim0.6']]


Jedvahj = pd.read_csv(patch + 'Jedvahj.txt',sep=',', index_col=None)
Jedvahj['Name'] = Jedvahj.index
Jedvahj.replace(to_replace=' ', value='_', regex=True, inplace= True)
Jedvahj.index=Jedvahj['Name']
Jedvahj = Jedvahj[['fb']]

Jiang = pd.read_csv(patch + 'Jiang.txt',sep=',', index_col='Name_ref')
#Jiang = Jiang[['fb']]

Li_Shao = pd.read_csv(patch+ 'Li_Shao.csv', index_col = 'Cluster')

In [5]:
qs = [0, 0.2, 0.5, 0.6]
columns = ['bin_frac','bin_frac_02','bin_frac_05', 'bin_frac_06']

df_comp = pd.DataFrame(columns=columns, index=data.index.unique())
for cluster in data.index.unique():
    for i in range(0, len(qs)):
        df.loc[cluster, columns[i]] = bin_frac(data.loc[cluster], qs[i])


for cluster in data.index.unique():
    for i in range(0, len(qs)):
        df_comp.loc[cluster, columns[i]] = corr_fb_by_similarity(df, columns[i], cluster,)
df_comp = df_comp.astype(float)

In [6]:
for cluster in donada.index:
    if cluster in df_comp.index:
        donada.loc[cluster, 'bin_frac_06'] = df_comp.loc[cluster, 'bin_frac_06']

for cluster in Jedvahj.index:
    if cluster in df_comp.index:
        Jedvahj.loc[cluster, 'bin_frac_06'] = df_comp.loc[cluster, 'bin_frac_06']

for cluster in Jiang.index:
    if cluster in df_comp.index:
        Jiang.loc[cluster, 'bin_frac_05'] = df_comp.loc[cluster, 'bin_frac_05']

for cluster in Li_Shao.index:
    if cluster in df_comp.index:
        Li_Shao.loc[cluster, 'bin_frac_02'] = df_comp.loc[cluster, 'bin_frac_02']
        
for cluster in Niu.index:
    if cluster in df_comp.index:
        Niu.loc[cluster, 'bin_frac'] = df_comp.loc[cluster, 'bin_frac']




donada.dropna(inplace=True)
Jedvahj.dropna(inplace=True)
Jiang.dropna(inplace=True)
Li_Shao.dropna(inplace=True)
Niu.dropna(inplace=True)

In [7]:
donada.describe().round(2)

       fbtotqlim0.6  e_fbtotqlim0.6  bin_frac_06
count        114.00          114.00       114.00
mean           0.21            0.05         0.31
std            0.13            0.03         0.07
min            0.06            0.01         0.17
25%            0.13            0.03         0.25
50%            0.17            0.04         0.31
75%            0.24            0.06         0.35
max            0.80            0.20         0.53

In [8]:
Jedvahj.describe().round(2)

         fb  bin_frac_06
count  7.00         7.00
mean   0.19         0.25
std    0.02         0.04
min    0.17         0.18
25%    0.17         0.25
50%    0.19         0.26
75%    0.22         0.27
max    0.22         0.29

In [9]:
Jiang.describe().round(2)

          ID     fb  bin_frac_05
count  17.00  17.00        17.00
mean   24.18   0.16         0.36
std    15.60   0.03         0.10
min     2.00   0.12         0.22
25%    12.00   0.15         0.27
50%    26.00   0.16         0.38
75%    38.00   0.17         0.43
max    50.00   0.21         0.60

In [10]:
Li_Shao.describe().round(2)

         fb  bin_frac_02
count  5.00         5.00
mean   0.40         0.41
std    0.06         0.08
min    0.30         0.30
25%    0.40         0.35
50%    0.41         0.40
75%    0.44         0.48
max    0.46         0.50

In [11]:
Niu.describe().round(2)

        fbin  fbin_err  bin_frac
count   9.00      9.00      9.00
mean   43.44      5.56      0.40
std     7.99      1.33      0.09
min    29.00      4.00      0.28
25%    41.00      4.00      0.33
50%    42.00      6.00      0.40
75%    47.00      6.00      0.44
max    55.00      8.00      0.55